# Generated by Django 5.2 on 2025-08-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_swapsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='swapsession',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
