# Generated by Django 5.2.5 on 2025-08-26 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_conversation_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='available_hours',
        ),
        migrations.RemoveField(
            model_name='swapsession',
            name='meeting_link',
        ),
    ]
