# Generated by Django 5.2.1 on 2025-08-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_rename_bio_profile_available_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
