# Generated by Django 5.2.5 on 2025-09-01 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_profile_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='embedding',
        ),
    ]
