# Generated by Django 5.2.5 on 2025-09-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_remove_profile_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
