# Generated by Django 5.2.5 on 2025-09-26 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_remove_profile_embedding_profile_average_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='comment',
        ),
    ]
